services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: agno-postgres
    environment:
      - POSTGRES_DB=agno_vectordb
      - POSTGRES_USER=agno_user
      - POSTGRES_PASSWORD=agno_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pgvector/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agno_user -d agno_vectordb"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 80s

volumes:
  postgres_data:
    driver: local 
